// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package account

import (
	"database/sql"
	"time"
)

// User account management table with security features and profile data
type User struct {
	ID       uint64 `json:"id"`
	Username string `json:"username"`
	Email    string `json:"email"`
	// Password hash (bcrypt/argon2)
	PasswordHash string `json:"password_hash"`
	// 0=inactive, 1=active, 2=disabled, 3=locked, 4=deleted
	Status            bool           `json:"status"`
	CreatedAt         time.Time      `json:"created_at"`
	UpdatedAt         time.Time      `json:"updated_at"`
	LastLoginAt       sql.NullTime   `json:"last_login_at"`
	FailedAttempts    uint8          `json:"failed_attempts"`
	LockedUntil       sql.NullTime   `json:"locked_until"`
	EmailVerifiedAt   sql.NullTime   `json:"email_verified_at"`
	PasswordChangedAt time.Time      `json:"password_changed_at"`
	DisplayName       sql.NullString `json:"display_name"`
	AvatarUrl         sql.NullString `json:"avatar_url"`
	// E.164 format (+country code)
	Phone      sql.NullString `json:"phone"`
	Locale     string         `json:"locale"`
	Timezone   string         `json:"timezone"`
	MfaEnabled bool           `json:"mfa_enabled"`
	// AES encrypted storage
	MfaSecret sql.NullString `json:"mfa_secret"`
	// Encrypted JSON array
	RecoveryCodes    sql.NullString `json:"recovery_codes"`
	PrivacyVersion   uint16         `json:"privacy_version"`
	MarketingConsent bool           `json:"marketing_consent"`
}
