// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package account

import (
	"context"
	"database/sql"
)

type Querier interface {
	CountUsers(ctx context.Context) (int64, error)
	CountUsersByStatus(ctx context.Context, status bool) (int64, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (sql.Result, error)
	DeleteUser(ctx context.Context, id uint64) error
	GetLockedUsers(ctx context.Context) ([]User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uint64) (User, error)
	GetUserByPhone(ctx context.Context, phone sql.NullString) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	GetUsersByEmailVerified(ctx context.Context) ([]User, error)
	GetUsersByLastLogin(ctx context.Context, arg GetUsersByLastLoginParams) ([]User, error)
	GetUsersWithMFA(ctx context.Context) ([]User, error)
	IncrementFailedAttempts(ctx context.Context, id uint64) error
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	ListUsersByStatus(ctx context.Context, arg ListUsersByStatusParams) ([]User, error)
	LockUser(ctx context.Context, arg LockUserParams) error
	UnlockUser(ctx context.Context, id uint64) error
	UpdateLastLogin(ctx context.Context, id uint64) error
	UpdateMFASettings(ctx context.Context, arg UpdateMFASettingsParams) error
	UpdateMarketingConsent(ctx context.Context, arg UpdateMarketingConsentParams) error
	UpdatePrivacyVersion(ctx context.Context, arg UpdatePrivacyVersionParams) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) error
	UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) error
	VerifyEmail(ctx context.Context, id uint64) error
}

var _ Querier = (*Queries)(nil)
