# Circle Center Application Configuration
# Copy this file to config.yaml and modify the values as needed

# Server configuration
server:
  # Server host address (0.0.0.0 for all interfaces)
  host: "0.0.0.0"
  # Server port
  port: 8080
  # Read timeout for HTTP requests
  read_timeout: "30s"
  # Write timeout for HTTP responses
  write_timeout: "30s"
  # Idle timeout for HTTP connections
  idle_timeout: "60s"

# Frontend configuration
frontend:
  # Base URL for frontend application
  base_url: "http://localhost:5173"

# Avatar configuration
avatar:
  # Maximum avatar upload size in bytes (default 2MB)
  max_upload_bytes: 2097152
  # Maximum allowed image quality when returning processed images (1-100)
  max_image_quality: 90

# MySQL database configuration
mysql:
  # MySQL server host
  host: "localhost"
  # MySQL server port
  port: 3306
  # MySQL username
  username: "root"
  # MySQL password (leave empty if no password)
  password: ""
  # Database name
  database: "circle_center"
  # Character set
  charset: "utf8mb4"
  # Parse time values
  parse_time: true
  # Location for time parsing
  loc: "Local"
  # Maximum number of open connections
  max_open_conns: 25
  # Maximum number of idle connections
  max_idle_conns: 5
  # Maximum lifetime of connections
  max_lifetime: "1h"
  # Enable multi-statement support for migrations
  multi_statement: true

# Redis configuration
redis:
  # Redis server host
  host: "localhost"
  # Redis server port
  port: 6379
  # Redis password (leave empty if no password)
  password: ""
  # Redis database number (0-15)
  db: 0
  # Connection pool size
  pool_size: 10
  # Minimum number of idle connections
  min_idle_conns: 5
  # Maximum number of retries
  max_retries: 3
  # Dial timeout
  dial_timeout: "5s"
  # Read timeout
  read_timeout: "3s"
  # Write timeout
  write_timeout: "3s"
  # Idle timeout
  idle_timeout: "5m"

# Mail configuration
mail:
  # SMTP server host
  host: "smtp.gmail.com"
  # SMTP server port
  port: 587
  # SMTP username (email address)
  username: ""
  # SMTP password (app password for Gmail)
  password: ""
  # From email address
  from: "no_reply@gmail.com"
  # TLS mode: "mandatory" (STARTTLS), "opportunistic" (STARTTLS with fallback), "ssl" (SSL), "none" (NoTLS)
  tls_mode: "ssl"

# JWT configuration
jwt:
  # JWT issuer
  issuer: "circle-center"
  # Token expiry time
  expiry_time: "168h"
  # RSA key size for JWT signing
  rsa_key_size: 2048
  # Directory to store JWT keys
  keys_directory: "config/keys"
  # Private key file name
  private_key_file: "jwt_private.pem"
  # Public key file name
  public_key_file: "jwt_public.pem"
  # Auto-generate keys if they don't exist
  auto_generate: true
