// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package manager

import (
	"context"
	"database/sql"
)

type Querier interface {
	CheckUserQuota(ctx context.Context, arg CheckUserQuotaParams) (CheckUserQuotaRow, error)
	CountActiveAPIKeys(ctx context.Context, projectID uint64) (int64, error)
	// Count collaborator projects (excluding owner role)
	CountCollaboratorProjects(ctx context.Context, userID uint64) (int64, error)
	CountIconsByStatus(ctx context.Context, arg CountIconsByStatusParams) (int64, error)
	CountItemsByResolution(ctx context.Context, arg CountItemsByResolutionParams) (int64, error)
	CountProjectCollaborators(ctx context.Context, projectID uint64) (int64, error)
	CountProjectIcons(ctx context.Context, projectID uint64) (int64, error)
	CountProjectRequests(ctx context.Context, projectID uint64) (int64, error)
	CountProjectsByOwner(ctx context.Context, ownerUserID uint64) (int64, error)
	CountProjectsByVisibility(ctx context.Context, visibility ProjectsVisibility) (int64, error)
	CountRequestItems(ctx context.Context, requestID uint64) (int64, error)
	CountRequestsByStatus(ctx context.Context, arg CountRequestsByStatusParams) (int64, error)
	// =============================================================================
	// ICONS MANAGEMENT
	// =============================================================================
	CreateIcon(ctx context.Context, arg CreateIconParams) (sql.Result, error)
	// =============================================================================
	// ICON REQUESTS MANAGEMENT
	// =============================================================================
	CreateIconRequest(ctx context.Context, arg CreateIconRequestParams) (sql.Result, error)
	// =============================================================================
	// PROJECTS MANAGEMENT
	// =============================================================================
	CreateProject(ctx context.Context, arg CreateProjectParams) (sql.Result, error)
	// =============================================================================
	// PROJECT API KEYS MANAGEMENT
	// =============================================================================
	CreateProjectAPIKey(ctx context.Context, arg CreateProjectAPIKeyParams) (sql.Result, error)
	// =============================================================================
	// REQUEST ITEMS MANAGEMENT
	// =============================================================================
	CreateRequestItem(ctx context.Context, arg CreateRequestItemParams) (sql.Result, error)
	// =============================================================================
	// USER PROJECT ROLES MANAGEMENT
	// =============================================================================
	CreateUserProjectRole(ctx context.Context, arg CreateUserProjectRoleParams) (sql.Result, error)
	// =============================================================================
	// USER QUOTAS MANAGEMENT
	// =============================================================================
	CreateUserQuota(ctx context.Context, arg CreateUserQuotaParams) (sql.Result, error)
	DeactivateAPIKey(ctx context.Context, arg DeactivateAPIKeyParams) error
	DeleteAPIKey(ctx context.Context, arg DeleteAPIKeyParams) error
	DeleteIcon(ctx context.Context, arg DeleteIconParams) error
	DeleteIconRequest(ctx context.Context, arg DeleteIconRequestParams) error
	DeleteProject(ctx context.Context, arg DeleteProjectParams) error
	DeleteProjectAPIKeys(ctx context.Context, projectID uint64) error
	DeleteProjectCollaborators(ctx context.Context, projectID uint64) error
	DeleteProjectIcons(ctx context.Context, projectID uint64) error
	DeleteProjectRequestItems(ctx context.Context, projectID uint64) error
	DeleteProjectRequests(ctx context.Context, projectID uint64) error
	DeleteRequestItem(ctx context.Context, arg DeleteRequestItemParams) error
	DeleteRequestItems(ctx context.Context, requestID uint64) error
	DeleteUserProjectRole(ctx context.Context, arg DeleteUserProjectRoleParams) error
	DeleteUserQuota(ctx context.Context, userID uint64) error
	GetDuplicateIcons(ctx context.Context, projectID uint64) ([]GetDuplicateIconsRow, error)
	GetIconByComponent(ctx context.Context, arg GetIconByComponentParams) (Icon, error)
	GetIconByID(ctx context.Context, id uint64) (Icon, error)
	GetIconRequestByID(ctx context.Context, id uint64) (IconRequest, error)
	GetIconRequestByIDAndProject(ctx context.Context, arg GetIconRequestByIDAndProjectParams) (IconRequest, error)
	GetIconStats(ctx context.Context, projectID uint64) (GetIconStatsRow, error)
	GetIconWithRequestInfo(ctx context.Context, id uint64) (GetIconWithRequestInfoRow, error)
	GetItemStats(ctx context.Context, requestID uint64) (GetItemStatsRow, error)
	GetProjectAPIKeyByHash(ctx context.Context, tokenHash string) (ProjectApiKey, error)
	GetProjectAPIKeyByID(ctx context.Context, id uint64) (ProjectApiKey, error)
	GetProjectByID(ctx context.Context, id uint64) (Project, error)
	GetProjectByIDAndOwner(ctx context.Context, arg GetProjectByIDAndOwnerParams) (Project, error)
	GetProjectBySlug(ctx context.Context, arg GetProjectBySlugParams) (Project, error)
	GetProjectStats(ctx context.Context, ownerUserID uint64) (GetProjectStatsRow, error)
	// =============================================================================
	// COMPLEX QUERIES AND JOINS
	// =============================================================================
	GetProjectWithStats(ctx context.Context, id uint64) (GetProjectWithStatsRow, error)
	GetRequestItemByComponent(ctx context.Context, arg GetRequestItemByComponentParams) (RequestItem, error)
	GetRequestItemByID(ctx context.Context, id uint64) (RequestItem, error)
	GetRequestStats(ctx context.Context, projectID uint64) (GetRequestStatsRow, error)
	GetUserProjectRole(ctx context.Context, arg GetUserProjectRoleParams) (UserProjectRole, error)
	GetUserQuota(ctx context.Context, userID uint64) (UserQuota, error)
	// Lightweight ID fetch for collaborator projects (excluding owner role)
	ListCollaboratorProjectIDs(ctx context.Context, arg ListCollaboratorProjectIDsParams) ([]uint64, error)
	ListIconsByPackage(ctx context.Context, arg ListIconsByPackageParams) ([]Icon, error)
	ListIconsByStatus(ctx context.Context, arg ListIconsByStatusParams) ([]Icon, error)
	ListItemsByResolution(ctx context.Context, arg ListItemsByResolutionParams) ([]RequestItem, error)
	// Lightweight ID fetch for owner projects (useful for code-side merging/pagination)
	ListOwnedProjectIDs(ctx context.Context, arg ListOwnedProjectIDsParams) ([]uint64, error)
	ListProjectAPIKeys(ctx context.Context, projectID uint64) ([]ProjectApiKey, error)
	ListProjectCollaborators(ctx context.Context, projectID uint64) ([]ListProjectCollaboratorsRow, error)
	ListProjectIcons(ctx context.Context, arg ListProjectIconsParams) ([]Icon, error)
	ListProjectRequestItems(ctx context.Context, arg ListProjectRequestItemsParams) ([]RequestItem, error)
	ListProjectRequests(ctx context.Context, arg ListProjectRequestsParams) ([]IconRequest, error)
	ListProjectsByOwner(ctx context.Context, arg ListProjectsByOwnerParams) ([]Project, error)
	ListProjectsByVisibility(ctx context.Context, arg ListProjectsByVisibilityParams) ([]Project, error)
	ListPublicProjects(ctx context.Context, arg ListPublicProjectsParams) ([]Project, error)
	ListRecentActivity(ctx context.Context, arg ListRecentActivityParams) ([]ListRecentActivityRow, error)
	ListRequestItems(ctx context.Context, requestID uint64) ([]RequestItem, error)
	ListRequestsByStatus(ctx context.Context, arg ListRequestsByStatusParams) ([]IconRequest, error)
	ListUserProjects(ctx context.Context, userID uint64) ([]ListUserProjectsRow, error)
	SearchIcons(ctx context.Context, arg SearchIconsParams) ([]Icon, error)
	UpdateAPIKeyLastUsed(ctx context.Context, id uint64) error
	UpdateIcon(ctx context.Context, arg UpdateIconParams) error
	UpdateIconStatus(ctx context.Context, arg UpdateIconStatusParams) error
	UpdateItemResolution(ctx context.Context, arg UpdateItemResolutionParams) error
	UpdateProject(ctx context.Context, arg UpdateProjectParams) error
	UpdateProjectIconCount(ctx context.Context, arg UpdateProjectIconCountParams) error
	UpdateRequestArchivePath(ctx context.Context, arg UpdateRequestArchivePathParams) error
	UpdateRequestItem(ctx context.Context, arg UpdateRequestItemParams) error
	UpdateRequestStatus(ctx context.Context, arg UpdateRequestStatusParams) error
	UpdateUserProjectRole(ctx context.Context, arg UpdateUserProjectRoleParams) error
	UpdateUserQuota(ctx context.Context, arg UpdateUserQuotaParams) error
}

var _ Querier = (*Queries)(nil)
